name: Build Rustagent

on:
  pull_request:
  push:
    branches:
      - main
      - prerelease/*.*
jobs:
  release:
    name: PR Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace version number in cargo.toml
        run: sed -i "s|<SERVICE_VERSION>|0.1.0|g" cargo.toml 

      - name: Build
        run: >
          cargo publish
          --verbose
          --dry-run

