name: Build Rustagent

on:
  pull_request:
  push:
    branches:
      - main
      - prerelease/*.*
jobs:
  release:
    name: PR Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Build
        run: >
          cargo publish
          --verbose
          --dry-run

